import React from 'react';
import { jsPDF } from 'jspdf';

const Reports = ({ data }) => {
    if (!data || data.length === 0) return <div className="text-gray-500">No data available. Upload a CSV file.</div>;

    const totalEquipment = data.length;
    const criticalCount = data.filter(i => i.status === 'Critical').length;
    const warningCount = data.filter(i => i.status === 'Warning').length;
    const stableCount = data.filter(i => i.status === 'Stable').length;
    const avgPressure = (data.reduce((acc, curr) => acc + parseFloat(curr.pressure || 0), 0) / totalEquipment).toFixed(2);
    const avgTemp = (data.reduce((acc, curr) => acc + parseFloat(curr.temp || 0), 0) / totalEquipment).toFixed(2);

    const handleExport = () => {
        const doc = new jsPDF();
        const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

        // Title
        doc.setFontSize(22);
        doc.setTextColor(40, 116, 240); // Blue
        doc.text("Chemical Plant Performance Report", 20, 20);

        // Date
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0); // Black
        doc.text(`Date: ${currentDate}`, 20, 30);
        doc.setLineWidth(0.5);
        doc.line(20, 35, 190, 35);

        // Section 1: Executive Summary
        doc.setFontSize(16);
        doc.text("1. Executive Summary", 20, 50);

        doc.setFontSize(11);
        doc.setTextColor(100);
        const summaryText = `The system is currently monitoring ${totalEquipment} units of equipment. There are ${criticalCount} critical alerts and ${warningCount} warnings requiring immediate attention.`;
        const splitSummary = doc.splitTextToSize(summaryText, 170);
        doc.text(splitSummary, 20, 60);

        // Section 2: Key Metrics
        doc.setFontSize(16);
        doc.setTextColor(0);
        doc.text("2. Key Metrics", 20, 80);

        doc.setFontSize(12);
        let yPos = 90;
        doc.text(`Total Equipment: ${totalEquipment}`, 30, yPos); yPos += 10;
        doc.text(`Average Pressure: ${avgPressure} Bar`, 30, yPos); yPos += 10;
        doc.text(`Average Temperature: ${avgTemp} °C`, 30, yPos); yPos += 10;
        doc.text(`System Health Score: ${data.length > 0 ? Math.round((stableCount / totalEquipment) * 100) : 0}%`, 30, yPos);

        // Section 3: Status Breakdown
        yPos += 20;
        doc.setFontSize(16);
        doc.text("3. Status Breakdown", 20, yPos);

        yPos += 10;
        doc.setFontSize(12);
        doc.setTextColor(0, 128, 0); // Green
        doc.text(`Stable: ${stableCount} units`, 30, yPos);

        yPos += 10;
        doc.setTextColor(255, 165, 0); // Orange
        doc.text(`Warning: ${warningCount} units`, 30, yPos);

        yPos += 10;
        doc.setTextColor(255, 0, 0); // Red
        doc.text(`Critical: ${criticalCount} units`, 30, yPos);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by ChemAnalytics Web", 20, 280);

        doc.save("System_Report.pdf");
    };

    return (
        <div className="space-y-6">
            <div className="bg-[#1a1d21] p-6 rounded-xl border border-gray-800">
                <div className="flex justify-between items-center mb-6">
                    <h3 className="text-xl font-bold text-white">System Performance Report</h3>
                    <button
                        onClick={handleExport}
                        className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-medium transition-colors"
                    >
                        Export PDF
                    </button>
                </div>

                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                    <div className="p-4 bg-black/20 rounded-lg">
                        <div className="text-gray-400 text-sm">Total Units</div>
                        <div className="text-2xl font-bold text-white">{totalEquipment}</div>
                    </div>
                    <div className="p-4 bg-black/20 rounded-lg">
                        <div className="text-gray-400 text-sm">Critical Issues</div>
                        <div className="text-2xl font-bold text-red-500">{criticalCount}</div>
                    </div>
                    <div className="p-4 bg-black/20 rounded-lg">
                        <div className="text-gray-400 text-sm">Avg Pressure</div>
                        <div className="text-2xl font-bold text-blue-500">{avgPressure} Bar</div>
                    </div>
                    <div className="p-4 bg-black/20 rounded-lg">
                        <div className="text-gray-400 text-sm">Avg Temperature</div>
                        <div className="text-2xl font-bold text-orange-500">{avgTemp} °C</div>
                    </div>
                </div>

                <h4 className="text-lg font-semibold text-white mb-2">Analysis Summary</h4>
                <p className="text-gray-400 text-sm leading-relaxed">
                    The current system shows {criticalCount > 0 ? `critical alerts in ${criticalCount} units` : 'stable operations across all units'}.
                    Average operating pressure is maintaining at {avgPressure} Bar, which is {avgPressure > 5 ? 'above' : 'within'} nominal range.
                    Temperature regulation is {avgTemp > 90 ? 'requiring attention' : 'optimal'} with an average of {avgTemp}°C.
                </p>
            </div>
        </div>
    );
};

export default Reports;
